// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfPDNkyK6E4nNkViDT3oT3KB1ox-PeQBw',
    appId: '1:721783966481:web:98e9cb5f510074217e5ab0',
    messagingSenderId: '721783966481',
    projectId: 'movie-app-62290',
    authDomain: 'movie-app-62290.firebaseapp.com',
    storageBucket: 'movie-app-62290.firebasestorage.app',
    measurementId: 'G-9VYEMH9YJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMZJJ1bn28zaFCfHgvAKafp_x1YbIuwcE',
    appId: '1:721783966481:android:fbd6a7aa1ac81fc07e5ab0',
    messagingSenderId: '721783966481',
    projectId: 'movie-app-62290',
    storageBucket: 'movie-app-62290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD72LwTKUYnNmkP8PFbh8WUHK3UpUx7K5o',
    appId: '1:721783966481:ios:5ba238ae0537ced47e5ab0',
    messagingSenderId: '721783966481',
    projectId: 'movie-app-62290',
    storageBucket: 'movie-app-62290.firebasestorage.app',
    androidClientId: '721783966481-cccr2mlgit46bstamukd6v5lnj7ijedh.apps.googleusercontent.com',
    iosClientId: '721783966481-lp6ankqr8qsuu4r8jl529mdoh8ukp0rt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMoviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD72LwTKUYnNmkP8PFbh8WUHK3UpUx7K5o',
    appId: '1:721783966481:ios:5ba238ae0537ced47e5ab0',
    messagingSenderId: '721783966481',
    projectId: 'movie-app-62290',
    storageBucket: 'movie-app-62290.firebasestorage.app',
    androidClientId: '721783966481-cccr2mlgit46bstamukd6v5lnj7ijedh.apps.googleusercontent.com',
    iosClientId: '721783966481-lp6ankqr8qsuu4r8jl529mdoh8ukp0rt.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMoviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfPDNkyK6E4nNkViDT3oT3KB1ox-PeQBw',
    appId: '1:721783966481:web:841513e11834018e7e5ab0',
    messagingSenderId: '721783966481',
    projectId: 'movie-app-62290',
    authDomain: 'movie-app-62290.firebaseapp.com',
    storageBucket: 'movie-app-62290.firebasestorage.app',
    measurementId: 'G-1MLZQ4QJ6L',
  );
}
